language: node_js

node_js:
  - 4
  - 5
  - 6

sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9

env:
  global:
    - NODE_ENV=test
    - CXX=g++-4.9

cache:
  apt: true
  directories:
    - node_modules
    - example/node_modules

script:
  - npm run test:ci
